<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="3.5" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProductVersion>9.0.21022</ProductVersion>
    <SchemaVersion>2.0</SchemaVersion>
    <ProjectGuid>{D3BDBDF2-B305-48A2-9BD1-CE51C4F805FB}</ProjectGuid>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>Ebada.SCGL.CADLib</RootNamespace>
    <AssemblyName>Ebada.SCGL.CADLib</AssemblyName>
    <TargetFrameworkVersion>v3.5</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>..\output\client\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Autodesk.AutoCAD.Interop, Version=16.1.63.0, Culture=neutral, PublicKeyToken=eed84259d7cbf30b">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\Library\Autodesk.AutoCAD.Interop.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Autodesk.AutoCAD.Interop.Common, Version=16.2.54.0, Culture=neutral, PublicKeyToken=eed84259d7cbf30b">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\Library\Autodesk.AutoCAD.Interop.Common.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Ebada.Client.Common, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\Library\Ebada.Client.Common.dll</HintPath>
    </Reference>
    <Reference Include="Ebada.Components, Version=1.0.2.0, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\Library\Ebada.Components.dll</HintPath>
    </Reference>
    <Reference Include="System" />
    <Reference Include="System.Core">
      <RequiredTargetFramework>3.5</RequiredTargetFramework>
    </Reference>
    <Reference Include="System.Drawing" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Xml.Linq">
      <RequiredTargetFramework>3.5</RequiredTargetFramework>
    </Reference>
    <Reference Include="System.Data.DataSetExtensions">
      <RequiredTargetFramework>3.5</RequiredTargetFramework>
    </Reference>
    <Reference Include="System.Data" />
    <Reference Include="System.Xml" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="CAD.cs" />
    <Compile Include="FlashWindow.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <COMReference Include="stdole">
      <Guid>{00020430-0000-0000-C000-000000000046}</Guid>
      <VersionMajor>2</VersionMajor>
      <VersionMinor>0</VersionMinor>
      <Lcid>0</Lcid>
      <WrapperTool>primary</WrapperTool>
      <Isolated>False</Isolated>
    </COMReference>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="FlashWindow.resx">
      <DependentUpon>FlashWindow.cs</DependentUpon>
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ebada.Scgl.Model\Ebada.Scgl.Model.csproj">
      <Project>{FCE4B7F7-BDF8-40AE-8F28-88C624C32F25}</Project>
      <Name>Ebada.Scgl.Model</Name>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <None Include="byq.dwg" />
    <None Include="err.dwg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="fw.dwg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="gl.dwg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="hg.dwg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="hl.dwg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="rd.dwg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="s.dwg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="tl.dwg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="xl1.dwg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="xl2.dwg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="xq.dwg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
  <!-- To modify your build process, add your task inside one of the targets below and uncomment it. 
       Other similar extension points exist, see Microsoft.Common.targets.
  <Target Name="BeforeBuild">
  </Target>
  <Target Name="AfterBuild">
  </Target>
  -->
</Project>